
package gl;

extern class Context
{
var canvas:String;
var drawingBufferHeight:Int;
var drawingBufferWidth:Int;
var viewportHeight:Int;
var viewportWidth:Int;
var ACTIVE_ATTRIBUTES:Int;
var ACTIVE_TEXTURE:Int;
var ACTIVE_UNIFORMS:Int;
var ALIASED_LINE_WIDTH_RANGE:Int;
var ALIASED_POINT_SIZE_RANGE:Int;
var ALPHA:Int;
var ALPHA_BITS:Int;
var ALWAYS:Int;
var ARRAY_BUFFER:Int;
var ARRAY_BUFFER_BINDING:Int;
var ATTACHED_SHADERS:Int;
var BACK:Int;
var BLEND:Int;
var BLEND_COLOR:Int;
var BLEND_DST_ALPHA:Int;
var BLEND_DST_RGB:Int;
var BLEND_EQUATION:Int;
var BLEND_EQUATION_ALPHA:Int;
var BLEND_EQUATION_RGB:Int;
var BLEND_SRC_ALPHA:Int;
var BLEND_SRC_RGB:Int;
var BLUE_BITS:Int;
var BOOL:Int;
var BOOL_VEC2:Int;
var BOOL_VEC3:Int;
var BOOL_VEC4:Int;
var BROWSER_DEFAULT_WEBGL:Int;
var BUFFER_SIZE:Int;
var BUFFER_USAGE:Int;
var BYTE:Int;
var CCW:Int;
var CLAMP_TO_EDGE:Int;
var COLOR_ATTACHMENT0:Int;
var COLOR_BUFFER_BIT:Int;
var COLOR_CLEAR_VALUE:Int;
var COLOR_WRITEMASK:Int;
var COMPILE_STATUS:Int;
var COMPRESSED_TEXTURE_FORMATS:Int;
var CONSTANT_ALPHA:Int;
var CONSTANT_COLOR:Int;
var CONTEXT_LOST_WEBGL:Int;
var CULL_FACE:Int;
var CULL_FACE_MODE:Int;
var CURRENT_PROGRAM:Int;
var CURRENT_VERTEX_ATTRIB:Int;
var CW:Int;
var DECR:Int;
var DECR_WRAP:Int;
var DELETE_STATUS:Int;
var DEPTH_ATTACHMENT:Int;
var DEPTH_BITS:Int;
var DEPTH_BUFFER_BIT:Int;
var DEPTH_CLEAR_VALUE:Int;
var DEPTH_COMPONENT:Int;
var DEPTH_COMPONENT16:Int;
var DEPTH_FUNC:Int;
var DEPTH_RANGE:Int;
var DEPTH_STENCIL:Int;
var DEPTH_STENCIL_ATTACHMENT:Int;
var DEPTH_TEST:Int;
var DEPTH_WRITEMASK:Int;
var DITHER:Int;
var DONT_CARE:Int;
var DST_ALPHA:Int;
var DST_COLOR:Int;
var DYNAMIC_DRAW:Int;
var ELEMENT_ARRAY_BUFFER:Int;
var ELEMENT_ARRAY_BUFFER_BINDING:Int;
var EQUAL:Int;
var FASTEST:Int;
var FLOAT:Int;
var FLOAT_MAT2:Int;
var FLOAT_MAT3:Int;
var FLOAT_MAT4:Int;
var FLOAT_VEC2:Int;
var FLOAT_VEC3:Int;
var FLOAT_VEC4:Int;
var FRAGMENT_SHADER:Int;
var FRAMEBUFFER:Int;
var FRAMEBUFFER_ATTACHMENT_OBJECT_NAME:Int;
var FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE:Int;
var FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE:Int;
var FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL:Int;
var FRAMEBUFFER_BINDING:Int;
var FRAMEBUFFER_COMPLETE:Int;
var FRAMEBUFFER_INCOMPLETE_ATTACHMENT:Int;
var FRAMEBUFFER_INCOMPLETE_DIMENSIONS:Int;
var FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT:Int;
var FRAMEBUFFER_UNSUPPORTED:Int;
var FRONT:Int;
var FRONT_AND_BACK:Int;
var FRONT_FACE:Int;
var FUNC_ADD:Int;
var FUNC_REVERSE_SUBTRACT:Int;
var FUNC_SUBTRACT:Int;
var GENERATE_MIPMAP_HINT:Int;
var GEQUAL:Int;
var GREATER:Int;
var GREEN_BITS:Int;
var HIGH_FLOAT:Int;
var HIGH_INT:Int;
var INCR:Int;
var INCR_WRAP:Int;
var INT:Int;
var INT_VEC2:Int;
var INT_VEC3:Int;
var INT_VEC4:Int;
var INVALID_ENUM:Int;
var INVALID_FRAMEBUFFER_OPERATION:Int;
var INVALID_OPERATION:Int;
var INVALID_VALUE:Int;
var INVERT:Int;
var KEEP:Int;
var LEQUAL:Int;
var LESS:Int;
var LINEAR:Int;
var LINEAR_MIPMAP_LINEAR:Int;
var LINEAR_MIPMAP_NEAREST:Int;
var LINES:Int;
var LINE_LOOP:Int;
var LINE_STRIP:Int;
var LINE_WIDTH:Int;
var LINK_STATUS:Int;
var LOW_FLOAT:Int;
var LOW_INT:Int;
var LUMINANCE:Int;
var LUMINANCE_ALPHA:Int;
var MAX_COMBINED_TEXTURE_IMAGE_UNITS:Int;
var MAX_CUBE_MAP_TEXTURE_SIZE:Int;
var MAX_FRAGMENT_UNIFORM_VECTORS:Int;
var MAX_RENDERBUFFER_SIZE:Int;
var MAX_TEXTURE_IMAGE_UNITS:Int;
var MAX_TEXTURE_SIZE:Int;
var MAX_VARYING_VECTORS:Int;
var MAX_VERTEX_ATTRIBS:Int;
var MAX_VERTEX_TEXTURE_IMAGE_UNITS:Int;
var MAX_VERTEX_UNIFORM_VECTORS:Int;
var MAX_VIEWPORT_DIMS:Int;
var MEDIUM_FLOAT:Int;
var MEDIUM_INT:Int;
var MIRRORED_REPEAT:Int;
var NEAREST:Int;
var NEAREST_MIPMAP_LINEAR:Int;
var NEAREST_MIPMAP_NEAREST:Int;
var NEVER:Int;
var NICEST:Int;
var NONE:Int;
var NOTEQUAL:Int;
var NO_ERROR:Int;
var ONE:Int;
var ONE_MINUS_CONSTANT_ALPHA:Int;
var ONE_MINUS_CONSTANT_COLOR:Int;
var ONE_MINUS_DST_ALPHA:Int;
var ONE_MINUS_DST_COLOR:Int;
var ONE_MINUS_SRC_ALPHA:Int;
var ONE_MINUS_SRC_COLOR:Int;
var OUT_OF_MEMORY:Int;
var PACK_ALIGNMENT:Int;
var POINTS:Int;
var POLYGON_OFFSET_FACTOR:Int;
var POLYGON_OFFSET_FILL:Int;
var POLYGON_OFFSET_UNITS:Int;
var RED_BITS:Int;
var RENDERBUFFER:Int;
var RENDERBUFFER_ALPHA_SIZE:Int;
var RENDERBUFFER_BINDING:Int;
var RENDERBUFFER_BLUE_SIZE:Int;
var RENDERBUFFER_DEPTH_SIZE:Int;
var RENDERBUFFER_GREEN_SIZE:Int;
var RENDERBUFFER_HEIGHT:Int;
var RENDERBUFFER_INTERNAL_FORMAT:Int;
var RENDERBUFFER_RED_SIZE:Int;
var RENDERBUFFER_STENCIL_SIZE:Int;
var RENDERBUFFER_WIDTH:Int;
var RENDERER:Int;
var REPEAT:Int;
var REPLACE:Int;
var RGB:Int;
var RGB5_A1:Int;
var RGB565:Int;
var RGBA:Int;
var RGBA4:Int;
var SAMPLER_2D:Int;
var SAMPLER_CUBE:Int;
var SAMPLES:Int;
var SAMPLE_ALPHA_TO_COVERAGE:Int;
var SAMPLE_BUFFERS:Int;
var SAMPLE_COVERAGE:Int;
var SAMPLE_COVERAGE_INVERT:Int;
var SAMPLE_COVERAGE_VALUE:Int;
var SCISSOR_BOX:Int;
var SCISSOR_TEST:Int;
var SHADER_TYPE:Int;
var SHADING_LANGUAGE_VERSION:Int;
var SHORT:Int;
var SRC_ALPHA:Int;
var SRC_ALPHA_SATURATE:Int;
var SRC_COLOR:Int;
var STATIC_DRAW:Int;
var STENCIL_ATTACHMENT:Int;
var STENCIL_BACK_FAIL:Int;
var STENCIL_BACK_FUNC:Int;
var STENCIL_BACK_PASS_DEPTH_FAIL:Int;
var STENCIL_BACK_PASS_DEPTH_PASS:Int;
var STENCIL_BACK_REF:Int;
var STENCIL_BACK_VALUE_MASK:Int;
var STENCIL_BACK_WRITEMASK:Int;
var STENCIL_BITS:Int;
var STENCIL_BUFFER_BIT:Int;
var STENCIL_CLEAR_VALUE:Int;
var STENCIL_FAIL:Int;
var STENCIL_FUNC:Int;
var STENCIL_INDEX:Int;
var STENCIL_INDEX8:Int;
var STENCIL_PASS_DEPTH_FAIL:Int;
var STENCIL_PASS_DEPTH_PASS:Int;
var STENCIL_REF:Int;
var STENCIL_TEST:Int;
var STENCIL_VALUE_MASK:Int;
var STENCIL_WRITEMASK:Int;
var STREAM_DRAW:Int;
var SUBPIXEL_BITS:Int;
var TEXTURE:Int;
var TEXTURE0:Int;
var TEXTURE1:Int;
var TEXTURE2:Int;
var TEXTURE3:Int;
var TEXTURE4:Int;
var TEXTURE5:Int;
var TEXTURE6:Int;
var TEXTURE7:Int;
var TEXTURE8:Int;
var TEXTURE9:Int;
var TEXTURE10:Int;
var TEXTURE11:Int;
var TEXTURE12:Int;
var TEXTURE13:Int;
var TEXTURE14:Int;
var TEXTURE15:Int;
var TEXTURE16:Int;
var TEXTURE17:Int;
var TEXTURE18:Int;
var TEXTURE19:Int;
var TEXTURE20:Int;
var TEXTURE21:Int;
var TEXTURE22:Int;
var TEXTURE23:Int;
var TEXTURE24:Int;
var TEXTURE25:Int;
var TEXTURE26:Int;
var TEXTURE27:Int;
var TEXTURE28:Int;
var TEXTURE29:Int;
var TEXTURE30:Int;
var TEXTURE31:Int;
var TEXTURE_2D:Int;
var TEXTURE_BINDING_2D:Int;
var TEXTURE_BINDING_CUBE_MAP:Int;
var TEXTURE_CUBE_MAP:Int;
var TEXTURE_CUBE_MAP_NEGATIVE_X:Int;
var TEXTURE_CUBE_MAP_NEGATIVE_Y:Int;
var TEXTURE_CUBE_MAP_NEGATIVE_Z:Int;
var TEXTURE_CUBE_MAP_POSITIVE_X:Int;
var TEXTURE_CUBE_MAP_POSITIVE_Y:Int;
var TEXTURE_CUBE_MAP_POSITIVE_Z:Int;
var TEXTURE_MAG_FILTER:Int;
var TEXTURE_MIN_FILTER:Int;
var TEXTURE_WRAP_S:Int;
var TEXTURE_WRAP_T:Int;
var TRIANGLES:Int;
var TRIANGLE_FAN:Int;
var TRIANGLE_STRIP:Int;
var UNPACK_ALIGNMENT:Int;
var UNPACK_COLORSPACE_CONVERSION_WEBGL:Int;
var UNPACK_FLIP_Y_WEBGL:Int;
var UNPACK_PREMULTIPLY_ALPHA_WEBGL:Int;
var UNSIGNED_BYTE:Int;
var UNSIGNED_INT:Int;
var UNSIGNED_SHORT:Int;
var UNSIGNED_SHORT_4_4_4_4:Int;
var UNSIGNED_SHORT_5_5_5_1:Int;
var UNSIGNED_SHORT_5_6_5:Int;
var VALIDATE_STATUS:Int;
var VENDOR:Int;
var VERSION:Int;
var VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:Int;
var VERTEX_ATTRIB_ARRAY_ENABLED:Int;
var VERTEX_ATTRIB_ARRAY_NORMALIZED:Int;
var VERTEX_ATTRIB_ARRAY_POINTER:Int;
var VERTEX_ATTRIB_ARRAY_SIZE:Int;
var VERTEX_ATTRIB_ARRAY_STRIDE:Int;
var VERTEX_ATTRIB_ARRAY_TYPE:Int;
var VERTEX_SHADER:Int;
var VIEWPORT:Int;
var ZERO:Int;

public function activeTexture():Void;
public function attachShader(a:Shader,b:Shader):Void;
public function bindAttribLocation():Void;
public function bindBuffer(a:Int,b:Dynamic):Void;
public function bindFramebuffer():Void;
public function bindRenderbuffer():Void;
public function bindTexture():Void;
public function blendColor():Void;
public function blendEquation():Void;
public function blendEquationSeparate():Void;
public function blendFunc():Void;
public function blendFuncSeparate():Void;
public function bufferData(a:Int, b:js.html.Float32Array, c:Int):Void;
public function bufferSubData():Void;
public function checkFramebufferStatus():Void;
public function clear():Void;
public function clearColor(r:Float,g:Float,b:Float,a:Float):Void;
public function clearDepth():Void;
public function clearStencil():Void;
public function colorMask():Void;
public function compileShader(a:Shader):Void;
public function compressedTexImage2D():Void;
public function compressedTexSubImage2D():Void;
public function copyTexImage2D():Void;
public function copyTexSubImage2D():Void;
public function createBuffer():Dynamic;
public function createFramebuffer():Void;
public function createProgram():Shader;
public function createRenderbuffer():Void;
public function createShader(a:Int):Shader;
public function createTexture():Void;
public function cullFace():Void;
public function deleteBuffer():Void;
public function deleteFramebuffer():Void;
public function deleteProgram():Void;
public function deleteRenderbuffer():Void;
public function deleteShader():Void;
public function deleteTexture():Void;
public function depthFunc():Void;
public function depthMask():Void;
public function depthRange():Void;
public function detachShader():Void;
public function disable():Void;
public function disableVertexAttribArray():Void;
public function drawArrays():Void;
public function drawElements():Void;
public function enable(a:Int):Void;
public function enableVertexAttribArray(a:Dynamic):Void;
public function finish():Void;
public function flush():Void;
public function framebufferRenderbuffer():Void;
public function framebufferTexture2D():Void;
public function frontFace():Void;
public function generateMipmap():Void;
public function getActiveAttrib():Void;
public function getActiveUniform():Void;
public function getAttachedShaders():Void;
public function getAttribLocation(a:Shader,b:String):Dynamic;
public function getBufferParameter():Void;
public function getContextAttributes():Void;
public function getError():Void;
public function getExtension():Void;
public function getFramebufferAttachmentParameter():Void;
public function getParameter():Void;
public function getProgramInfoLog():Void;
public function getProgramParameter(a:Shader,b:Int):Int;
public function getRenderbufferParameter():Void;
public function getShaderInfoLog(a:Shader):Dynamic;
public function getShaderParameter(a:Shader,b:Int):Int;
public function getShaderPrecisionFormat():Void;
public function getShaderSource():Void;
public function getSupportedExtensions():Void;
public function getTexParameter():Void;
public function getUniform():Void;
public function getUniformLocation(a:Shader,b:String):Dynamic;
public function getVertexAttrib():Void;
public function getVertexAttribOffset():Void;
public function hint():Void;
public function isBuffer():Void;
public function isContextLost():Void;
public function isEnabled():Void;
public function isFramebuffer():Void;
public function isProgram():Void;
public function isRenderbuffer():Void;
public function isShader():Void;
public function isTexture():Void;
public function lineWidth():Void;
public function linkProgram(a:Shader):Void;
public function pixelStorei():Void;
public function polygonOffset():Void;
public function readPixels():Void;
public function renderbufferStorage():Void;
public function sampleCoverage():Void;
public function scissor():Void;
public function shaderSource(a:Shader,b:String):Void;
public function stencilFunc():Void;
public function stencilFuncSeparate():Void;
public function stencilMask():Void;
public function stencilMaskSeparate():Void;
public function stencilOp():Void;
public function stencilOpSeparate():Void;
public function texImage2D():Void;
public function texParameterf():Void;
public function texParameteri():Void;
public function texSubImage2D():Void;
public function uniform1f():Void;
public function uniform1fv():Void;
public function uniform1i():Void;
public function uniform1iv():Void;
public function uniform2f():Void;
public function uniform2fv():Void;
public function uniform2i():Void;
public function uniform2iv():Void;
public function uniform3f():Void;
public function uniform3fv():Void;
public function uniform3i():Void;
public function uniform3iv():Void;
public function uniform4f():Void;
public function uniform4fv():Void;
public function uniform4i():Void;
public function uniform4iv():Void;
public function uniformMatrix2fv():Void;
public function uniformMatrix3fv():Void;
public function uniformMatrix4fv():Void;
public function useProgram(a:Shader):Void;
public function validateProgram():Void;
public function vertexAttrib1f():Void;
public function vertexAttrib1fv():Void;
public function vertexAttrib2f():Void;
public function vertexAttrib2fv():Void;
public function vertexAttrib3f():Void;
public function vertexAttrib3fv():Void;
public function vertexAttrib4f():Void;
public function vertexAttrib4fv():Void;
public function vertexAttribPointer():Void;
public function viewport():Void;

}